name: Build OpenCV for ARM7L

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build OpenCV Python package for ARM7L
        run: |
          docker buildx create --name mybuilder --use
          docker buildx build --platform linux/arm/v7 -t my-arm7l-opencv --output type=local,dest=./output .

      - name: Upload OpenCV Wheel
        uses: actions/upload-artifact@v3
        with:
          name: opencv-python-arm7l-wheel
          path: ./output/*.whl
